# PyTorch Lesson

In [4]:
import torch

In [5]:
x = torch.empty(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Tensor Basic

## Addition, Subtraction, Multiplication, and Divition Elementwise

In [6]:
x = torch.rand(2,2)
y = torch.rand(2,2)

print(x)
print(y)

tensor([[0.0892, 0.9104],
        [0.6999, 0.3839]])
tensor([[0.1203, 0.3482],
        [0.8744, 0.7207]])


In [17]:
z = x + y
print(z)
print(torch.add(x,y))

tensor([[0.3754, 4.7876],
        [3.9015, 1.9599]])
tensor([[0.3754, 4.7876],
        [3.9015, 1.9599]])


In [16]:
print(y.add_(x))

tensor([[0.2862, 3.8772],
        [3.2016, 1.5759]])


In [13]:
print(torch.sub(x,y))

tensor([[ 0.0705, -0.2355],
        [-0.4020, -0.0402]])


In [10]:
print(torch.mul(x,y))

tensor([[0.0187, 1.1459],
        [1.1019, 0.4241]])


In [11]:
print(y.mul_(x))

tensor([[0.0187, 1.1459],
        [1.1019, 0.4241]])


In [12]:
print(torch.div(x,y))

tensor([[4.7747, 0.7945],
        [0.6352, 0.9053]])


In [20]:
x = torch.rand(5,3)

## Slicing

In [23]:
print(x)
print(x[1,1].item())

tensor([[0.4961, 0.7317, 0.2773],
        [0.1419, 0.8032, 0.1173],
        [0.6260, 0.1631, 0.7891],
        [0.5656, 0.3709, 0.0839],
        [0.9200, 0.6065, 0.2569]])
0.8031861782073975


## Reshape

In [24]:
x = torch.rand(4,4)
print(x)

tensor([[0.6539, 0.2487, 0.5205, 0.2349],
        [0.9733, 0.5342, 0.6050, 0.5881],
        [0.5272, 0.8536, 0.8069, 0.9111],
        [0.6199, 0.1165, 0.7777, 0.6192]])


In [40]:
y = x.view(-1, 8)
print(y.size())

torch.Size([2, 8])


## Numpy to Torch

In [41]:
import numpy as np

In [47]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


- problem with torch + numpy in CPU ---> use the same memory location

In [48]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [49]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [55]:
a = np.ones(5)
b = torch.from_numpy(a)

a += 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


Instead, we do

In [58]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    
    y = y.to(device)
    
    z = x + y
    z = z.to("cpu")
    
    z = z.numpy()
    print(z)
    print(x)
    print(y)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], device='cuda:0')
tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [ ]:
x = torch.ones(5, requires_grad=True)
print(x)